apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  namespace: flows-pen-test
  labels:
    app: curl-test
    purpose: mTLS-testing
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: ["sleep", "3600"]
    env:
    # Direct connection variables (will be blocked by network policy)
    - name: DIRECT_URL
      value: "https://r1r2.3disystems.com:443"
    - name: DIRECT_DOMAIN
      value: "r1r2.3disystems.com"
    - name: DIRECT_PORT
      value: "443"
    
    # HAProxy connection variables (working mTLS path)
    - name: HAPROXY_URL
      value: "http://haproxy-egress:8443"
    - name: HAPROXY_SVC
      value: "haproxy-egress"
    - name: HAPROXY_PORT
      value: "8443"
    - name: HOST_HEADER
      value: "r1r2.3disystems.com"
    
    # Test commands as variables
    - name: CMD_DIRECT
      value: "curl -vk https://r1r2.3disystems.com:443"
    - name: CMD_DIRECT_TIMEOUT
      value: "curl -vk --connect-timeout 5 https://r1r2.3disystems.com:443"
    - name: CMD_VIA_HAPROXY
      value: "curl -v http://haproxy-egress:8443 -H 'Host: r1r2.3disystems.com'"
    - name: CMD_HAPROXY_HEALTH
      value: "curl -v http://haproxy-egress:8443/health -H 'Host: r1r2.3disystems.com'"
    
    # DNS and network test variables
    - name: DNS_SERVER
      value: "8.8.8.8"
    - name: TEST_ENDPOINT
      value: "r1r2.3disystems.com"
    - name: EXPECTED_IP
      value: "13.91.0.38"
    
    # Curl options
    - name: CURL_OPTS
      value: "-v --connect-timeout 5"
    - name: CURL_OPTS_INSECURE
      value: "-vk --connect-timeout 5"
